language: cpp

script:
  - g++ --version && cmake --version
  - ./configure && cd build && make && cd -
  - cd build && ctest

matrix:
  include:
  - compiler: gcc
    os: linux
    dist: focal
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev

  - compiler: clang
    os: linux
    dist: focal
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev

  - compiler: gcc
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev

  - compiler: clang
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev
