language: cpp

script:
  - g++ --version && cmake --version
  - ./configure && cd build && make && cd -
  - cd build && ctest

matrix:
  include:
  - os: linux
    dist: focal
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev
    compiler:
    - gcc
    - clang

  - os: linux
    dist: bionic
    addons:
      apt:
        packages:
        - cpputest
        - libcpputest-dev
    compiler:
    - gcc
    - clang

